### ISSUE TITLE
Gracefully handle port in use

### ISSUE THREAD

**Issue by jayvdb** [8eecf0d2/netlify-local#27]
```
[netlify-local] starting http server
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8100
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
```

It is fairly common to be running multiple instances of an app framework in development, with ports preselected by a tool such as netlify-local .

`ionic service` looks for the next available port, and iirc `ng serve` does the same.

**Comment by 8eecf0d2** [comment]
Will look into this and how other's handle next available port (when none specified).

_PS. Thanks for all the issues!_

**Comment by jayvdb** [comment]
fwiw, that output was when called with `--port 8100` .  I would expect it to fail nicely, or give a warning and startup on 8101 .

Thanks for the really cool project.  I'm hoping to get it into my e2e jobs. It is a bit bigger than what i need, as we dont use lambda functions (yet..), but it takes care of the redirects without me needing to build some custom http serve logic.  Very happy if we can get the other two solved.  This port one is much less of a problem.

**Comment by 8eecf0d2** [comment]
> fwiw, that output was when called with `--port 8100` . I would expect it to fail nicely, or give a warning and startup on 8101 .

Happy to try next port when none is set, otherwise if `--port` is set I'd prefer to gracefully `throw` with nicer error message.

Thanks for the kind words! I'm in a similar situation and [netlify/netlify-lambda](https://github.com/netlify/netlify-lambda) just wasn't quite enough at the time. However they're cooking up a lot of interesting things themselves which may end up replacing **netlify-local** - might be worthwhile keeping an eye on https://github.com/netlify/netlify-lambda/issues/75

**Comment by 8eecf0d2** [comment]
If `port` is set within options and not available, and error will be thrown.
If `port` is **not** set within options and default (`9000`) is not available, it will use [`get-port`](https://www.npmjs.com/package/get-port) package to find available port.
